# Generated by Django 4.1 on 2022-09-09 08:52

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserPackageRel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_pass_date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('best_pass_date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('points', models.IntegerField(blank=True, null=True)),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_rel', to='quiz.questionpackage')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='package_rel', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddConstraint(
            model_name='userpackagerel',
            constraint=models.UniqueConstraint(fields=('package', 'user'), name='unique_package_user'),
        ),
    ]
