# Generated by Django 4.1 on 2022-09-27 11:39

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_userpackagerel_userpackagerel_unique_package_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpackagerel',
            name='best_pass_date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='userpackagerel',
            name='first_pass_date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
    ]
